### ISSUE TITLE
-upload probably broken - Been stuck for an hour

### ISSUE THREAD

**Issue by shadow01148** [MaximumADHD/Source2Roblox#12]
![image](https://user-images.githubusercontent.com/76457846/133708317-acd71419-2487-4f29-9158-0515a4168fe6.png)

I'll keep the .exe running incase something happens.

Update: New error this time: 

The remote server returned an error: (422) Inappropriate name or description..

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.

**Comment by MaximumADHD** [comment]
I'll see if I can provide a better metric for what threads are hanging eventually.

**Comment by umustbeloggedintododat** [comment]
im having this issue but with rp_unioncity_day (custom gmod map)

**Comment by umustbeloggedintododat** [comment]
![image](https://user-images.githubusercontent.com/54049600/152907711-15f9f4e5-d1f7-499a-a1bd-eabccf274d07.png)
