### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by Spenkir** [MaximumADHD/Source2Roblox#13]
Is there any way to make one large map instead of having it being add up by each part like d1_trainstation_01 and so on.
Any help would be awesome.

**Comment by MaximumADHD** [comment]
Nope, it is not possible at this time and it likely never will be. Roblox only supports one texture being applied to each MeshPart and texture uploads are capped to a 1024x1024 resolution. If you were to try and pack all the textures into one image you would have no texture resolution left. I pack it pretty tightly FWIW, you just have to be patient with the upload process.
