### ISSUE TITLE
Error while converting a map

### ISSUE THREAD

**Issue by cebar2002** [MaximumADHD/Source2Roblox#14]
I do not know if this is a bug or something else because I am quite a newbie at this but I am quite struck by this passing program VALVe games to Roblox, I was testing and this happened to me
![image](https://user-images.githubusercontent.com/88451311/134360672-8f84b73d-a29b-4f13-ab5a-101f9fa37455.png)

**Comment by shadow01148** [comment]
You need ValveKeyValue and RobloxFileFormat. (Listed in the README.md file)

**Comment by shadow01148** [comment]
> Where i should've put the folders?
> ![image](https://user-images.githubusercontent.com/88451311/134704875-92bf2d88-d449-48b1-b8f0-f35767b76767.png)

That's fine

**Comment by cebar2002** [comment]
Then, what is wrong?

**Comment by MaximumADHD** [comment]
The `-master` and `-main` suffixes should not be on those folder names.

**Comment by RealKalsep** [comment]
As said, remove the -main and -master. It took me some experimenting to know what structure is correct.

**Comment by cebar2002** [comment]
Now i have other bugs
![image](https://user-images.githubusercontent.com/88451311/134778669-49832287-1a2f-4168-ab8b-1495b644b536.png)

**Comment by shadow01148** [comment]
Roblox-File-Format.dll on the Roblox-File-Format folder, just put it in on ./bin/Debug/. On the missing packages, run Update-Package -reinstall (Package Manager Console)

**Comment by cebar2002** [comment]
i used the command and try again but this appears
![image](https://user-images.githubusercontent.com/88451311/134815571-49c7b1cb-ee86-4d7c-8bdc-31dfd0baa6a6.png)
![image](https://user-images.githubusercontent.com/88451311/134815599-afcfb447-659b-422e-a294-b7fbfae0a35e.png)

**Comment by shadow01148** [comment]
> Roblox-File-Format.dll on the Roblox-File-Format folder, just put it in on ./bin/Debug/. On the missing packages, run Update-Package -reinstall (Package Manager Console)

Like I said, put RobloxFileFormat.dll on ./bin/Debug

![image](https://user-images.githubusercontent.com/76457846/134826456-5f75e074-af74-4ba4-8385-2ff0ba1d033d.png)

**Comment by cebar2002** [comment]
What i should do?
![image](https://user-images.githubusercontent.com/88451311/134828808-6e3a59ab-1f9d-4935-b7cc-4fca7a8725ba.png)

**Comment by shadow01148** [comment]
It means it worked, add -map or a -model command line argument (Listed in the README.md file)

**Comment by cebar2002** [comment]
@shadow01148 
![image](https://user-images.githubusercontent.com/88451311/134829398-c8f97859-a9be-4d5d-94f0-590c59ff8e0d.png)
the map are obligatory?

**Comment by shadow01148** [comment]
Not required.
