### ISSUE TITLE
Error while converting a map

### ISSUE THREAD

**Issue by falsvvalt** [MaximumADHD/Source2Roblox#15]
![h](https://user-images.githubusercontent.com/66258892/134824225-17bc4898-ccb9-473f-87c2-6b28a3b95724.PNG)

ive tried doing Update-Package -reinstall multiple times but it doesnt seem to do much, very confused.

**Comment by shadow01148** [comment]
Open RobloxFileFormat.sln and run Update-Package -reinstall from there. (Package Manager Console)

**Comment by falsvvalt** [comment]
Everything works perfectly! Thanks.
