### ISSUE TITLE
"Attempted To Divide By Zero" Error In StaticProps.cs

### ISSUE THREAD

**Issue by Gamer3789** [MaximumADHD/Source2Roblox#25]
![image](https://user-images.githubusercontent.com/58898564/137234123-ba3f3a33-d999-4296-bf8b-772ebe576ff8.png)
I attempted to import a community server map (specifically "Achievement Engineer") and I was presented with this error. Perhaps the map's lack of static props caused this error to pop up. Creating an "if staticprops == 0 then" statement in the form of C# might patch it.

**Comment by MaximumADHD** [comment]
Fixed!
https://github.com/MaximumADHD/Source2Roblox/commit/69c8358b8abcbdb879d3fff171052dbdf46c4f13
