### ISSUE TITLE
Visual Studio 2019 Is No Longer Available

### ISSUE THREAD

**Issue by Gamer3789** [MaximumADHD/Source2Roblox#33]
Visual Studio 2022 is now our only option for downloading Visual Studio. Will 2022 perhaps work with Source2ROBLOX?

**Comment by RealKalsep** [comment]
It is still downloadable on `https://my.visualstudio.com/` as `Visual Studio Community 2019 (version 16.11)`.

**Comment by RealKalsep** [comment]
Oh, and as by 2022 working with Source2Roblox, I don't know. Haven't tested yet. @MaximumADHD must confirm this, or someone else who would be interested in testing.
