### ISSUE TITLE
Errors with everything.

### ISSUE THREAD

**Issue by Erestas** [MaximumADHD/Source2Roblox#40]
I have tried and done everything that had been instructed but I have been stumped, If someone would be kind enough to please guide me through the process of setting up these programs I would really appreciate it.

If you would like to try and help me please contact me on discord **Erestas#2720** **Or just comment** on this issue request.

If I get this explained to me I will help any other unexperienced users to get this program working.

**Comment by shadow01148** [comment]
I can't help you if you don't give me the error message.
