### ISSUE TITLE
"can't find any source games" error no matter how many times i try to fix it

### ISSUE THREAD

**Issue by TinyTopHat** [MaximumADHD/Source2Roblox#41]
so i have been trying to use r2s for around 20 minutes now. i saw somewhere in a flag with this exact issue saying it looks for the hl2 folder in the games, so i created one and i have tried to put the hl2 folder in almost every folder in the garry's mod folder and it still hasn't detected i have a source game on my pc

video with the error: https://youtu.be/cwX7f6CgZwg

**Comment by TinyTopHat** [comment]
so i just realized this is on the wrong one but i think the problems might be universal between the two versions

**Comment by shadow01148** [comment]
Nope.

**Comment by XxSuperLuigi350xX** [comment]
yeah ive had that issue for the longest time now hopefully it can get fixed soon
