### ISSUE TITLE
What is gameinfo.txt

### ISSUE THREAD

**Issue by jack8699** [MaximumADHD/Source2Roblox#49]
![image](https://user-images.githubusercontent.com/60725996/169679471-f4a03237-c776-4312-95fc-c647ac584b11.png)

is there a template or reference so I know what a gameinfo.txt should look like?

**Comment by PhoenixWhitefire** [comment]
It's path should be "<drive>:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\gameinfo.txt", but it should already exist if you have TF2 installed.

Here's the contents of it on my PC:
`"GameInfo"
{
	game	"Team Fortress 2"
	type multiplayer_only
	nomodels 1
	nohimodel 1
	nocrosshair 0
	hidden_maps
	{
		"test_speakers"		1
		"test_hardware"		1
	}
	nodegraph 0
	GameData	"tf.fgd"
	InstancePath "maps/instances/"
	advcrosshair 1
	supportsvr 1


	FileSystem
	{
		SteamAppId				440
		
		//
		// Setup engine search paths.
		//
		// If a search path contains "_english", and the current language is not english, then
		// another search path will be inserted above the english one by replacing "_english" with
		// the appropriate language.
		//
		// To debug how the engine has parsed this file, type "path" at the console.
		//
		// Search paths are relative to the base directory, which is where hl2.exe is found.
		//
		// |gameinfo_path| points at the directory where gameinfo.txt is.
		// |all_source_engine_paths| points at the directory cintaining HL2 shared content.
		//
		SearchPaths
		{

			// First, mount all user customizations.  This will search for VPKs and subfolders
			// and mount them in alphabetical order.  The easiest way to distribute a mod is to
			// pack up the custom content into a VPK.  To "install" a mod, just drop it in this
			// folder.
			//
			// Note that this folder is scanned only when the game is booted.
			game+mod+custom_mod	tf/custom/*

			// We search VPK files before ordinary folders, because most files will be found in
			// VPK and we can avoid making thousands of file system calls to attempt to open files
			// in folders where they don't exist.  (Searching a VPK is much faster than making an operating
			// system call.)
			game_lv				tf/tf2_lv.vpk
			game+mod			tf/tf2_textures.vpk
			game+mod			tf/tf2_sound_vo_english.vpk
			game+mod			tf/tf2_sound_misc.vpk
			game+mod+vgui		tf/tf2_misc.vpk
			game				|all_source_engine_paths|hl2/hl2_textures.vpk
			game				|all_source_engine_paths|hl2/hl2_sound_vo_english.vpk
			game				|all_source_engine_paths|hl2/hl2_sound_misc.vpk
			game+vgui			|all_source_engine_paths|hl2/hl2_misc.vpk
			platform+vgui			|all_source_engine_paths|platform/platform_misc.vpk

			// Now search loose files.  We'll set the directory containing the gameinfo.txt file
			// as the first "mod" search path (after any user customizations).  This is also the one
			// that's used when writing to the "mod" path.
			mod+mod_write+default_write_path		|gameinfo_path|.

			// Add the TF directory as a game search path.  This is also where where writes
			// to the "game" path go.
			game+game_write		tf

			// Where the game's binaries are
			gamebin				tf/bin

			// Last, mount in shared HL2 loose files
			game				|all_source_engine_paths|hl2
			platform			|all_source_engine_paths|platform

			// Random files downloaded from gameservers go into a seperate directory, so
			// that it's easy to keep those files segregated from the official game files
			// or customizations intentially installed by the user.
			//
			// This directory is searched LAST.  If you visit a server and download
			// a custom model, etc, we don't want that file to override the default
			// game file indefinitely (after you have left the server).  Servers CAN have
			// custom content that overrides the default game files, it just needs to be
			// packed up in the .bsp file so that it will be mounted as a map search pack.
			// The map search pack is mounted at the top of the search path list,
			// but only while you are connected that server and on that map.
			game+download	tf/download
		}
	}

	ToolsEnvironment
	{
		"Engine"			"Source"
		"UseVPLATFORM"		"1"
		"PythonVersion"		"2.7"
		"PythonHomeDisable"	"1"
	}
}
`

**Comment by shadow01148** [comment]
It is located in Team Fortress 2/tf.
