### ISSUE TITLE
Props Crammed Together At 0,0,0

### ISSUE THREAD

**Issue by Gamer3789** [MaximumADHD/Source2Roblox#51]
Just tried to import a Backrooms map from the workshop, only to be presented with THIS upon opening Studio.
![image](https://user-images.githubusercontent.com/58898564/171486205-f9dbeb7b-9811-415f-a5af-c6a9d3a63925.png)
The props' positions are all set to 0,0,0.

**Comment by MaximumADHD** [comment]
I did notice this recently. Seems to be a weird regression with my file format library.
I’ll take a look soon.

**Comment by MaximumADHD** [comment]
Issue with Roblox-File-Format should be resolved now.

**Comment by MaximumADHD** [comment]
Did you reinstall RFF?
