### ISSUE TITLE
MeshParts dissapering at some camera angles? + CFrame bug

### ISSUE THREAD

**Issue by AlexR32** [MaximumADHD/Source2Roblox#52]
Hello, is there any way i can fix this, maybe i need enable something in roblox?

https://user-images.githubusercontent.com/58864658/172662482-c173c9e3-d8d5-4459-bd15-18181bc2aa77.mp4

Also i found that when map is compiling there is error with prop cframe multiply operator:
In Source2Roblox/Geometry/MeshBuilder line 1196
And in Source2Roblox/Util/Extensions line 238

So i had to manually comment model.PivotTo to prevent program crash on map compile
It seems that it cant read prop cframe and instead making it null so multiply func breaks
I think it's familiar with #10
Also it happens with ropes when GetCFrame tries to divide origin and STUDS_TO_VMF

**Comment by AlexR32** [comment]
So after some testing and debugging i think that model.PivotTo(cf) is broken
i tried excepting props that have null cframe with `if (prop.CFrame == null) continue;`
but that didn't help, their position still on 0,0,0

**Comment by AlexR32** [comment]
nvm about PivotTo thing, I found real problem with CFrame
CFrame in Entity.cs from line 168 to 172 calculating zero position for some reason
could it be my cs:s bsp files?

**Comment by AlexR32** [comment]
I fixed this problem with props in 0,0,0 position and clusters not render right
CFrame.Position have wrong args it should be `m14, m24, m34` but its `m41, m42, m43` instead

also some dynamic props dont have origin and angles properties
and static props have wrong position and rotation sometimes

**Comment by MaximumADHD** [comment]
Ooh goodie. This is why I need to start unit testing my library to catch stuff like that.
I'll get a patch made asap.

**Comment by Gamer3789** [comment]
There's also an issue regarding the materials. Back in October of 2021, GM_Construct was uploaded with the sand texture wrapping around the lake like it should be:
![image](https://user-images.githubusercontent.com/58898564/174461066-aed442a3-ff28-401c-9e56-738d4bf6ec6e.png)
But now, when you import GM_Construct, the only texture that wraps around the lake is grass; no sand in sight.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/58898564/174461067-4fe18a02-a491-41fa-82db-48ee532dc1e3.png">
Perhaps you could consider fixing this soon. Clearly a minor bug, but I feel it's important it gets fixed.

**Comment by AlexR32** [comment]
> Also can you fix Entity.Get, it gets null origin vector3 and angles vector3 This causes Entity.CFrame and rope origin to be null as well

I found that origin field becomes string somewhere after Source2Roblox.World.Types.Entity.ReadField function because if you write ReadField result to console it will be normal but if you print origin in Source2Roblox.World.Types.Entity.CFrame it will be a string

**Comment by Gamer3789** [comment]
> @MaximumADHD 
> I get what you're describing but I never actually had smooth texture blending like that implemented. The best I had was making it switch between one material or the other depending on whether the alpha blending value passed a 50% threshold. I did have an idea for how I could bring it back which I'll explore when I have the time again, but it's never going to be smoothly blended.

Perhaps you could remove this 50% threshold change then, as I feel the maps I've imported in the past and future maps I will import will look better this way. Shouldn't be too hard for you to bring it back, hopefully.
