### ISSUE TITLE
StaticProps.cs Error on Black Mesa - System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by shadow01148** [MaximumADHD/Source2Roblox#6]
Exception thrown: 'System.IndexOutOfRangeException' in Source2Roblox.exe
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in Source2Roblox.exe
Index was outside the bounds of the array.

Error began on Clumping faces... 4925/4957

**Comment by MaximumADHD** [comment]
Alright, this should hopefully be patched now:
https://github.com/MaximumADHD/Source2Roblox/commit/95d56cda24b6108c2e0b6a1761084b116ab65041
